try:
    a=int(input("Hey,Enter a number"))
    print(a)
except Exception as e:
        print(e)

else: #  this run  when try is successful 
    print("I am inside else")



